Repository JamesTKhan/Mundus, pull requests merged in 2023-04, with the labels that each got.

#144 Fix look around shortcut info
  editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/KeyboardShortcutsDialog.kt
Labels: bug

#148 Add convenience search methods to SceneGraph
  commons/src/main/com/mbrlabs/mundus/commons/scene3d/GameObject.java
  commons/src/main/com/mbrlabs/mundus/commons/scene3d/SceneGraph.java
  commons/src/main/com/mbrlabs/mundus/commons/utils/LightUtils.java
  commons/src/test/com/mbrlabs/mundus/commons/SceneGraphTest.java
  commons/src/test/com/mbrlabs/mundus/commons/test/SceneGraphTest.java
  gdx-runtime/CHANGES
Labels: enhancement

#146 Helper lines
  editor/CHANGES
  editor/src/main/com/mbrlabs/mundus/editor/Editor.kt
  editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLineShape.kt
  editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLineType.kt
  editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HelperLines.kt
  editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/HexagonHelperLineShape.kt
  editor/src/main/com/mbrlabs/mundus/editor/core/helperlines/RectangleHelperLineShape.kt
  editor/src/main/com/mbrlabs/mundus/editor/core/project/ProjectContext.java
  editor/src/main/com/mbrlabs/mundus/editor/events/TerrainAddedEvent.kt
  editor/src/main/com/mbrlabs/mundus/editor/events/TerrainRemovedEvent.kt
  editor/src/main/com/mbrlabs/mundus/editor/events/TerrainVerticesChangedEvent.kt
  editor/src/main/com/mbrlabs/mundus/editor/terrain/HeightMapGenerator.java
  editor/src/main/com/mbrlabs/mundus/editor/terrain/PerlinNoiseGenerator.java
  editor/src/main/com/mbrlabs/mundus/editor/terrain/Terraformer.java
  editor/src/main/com/mbrlabs/mundus/editor/tools/brushes/TerrainBrush.java
  editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/AddTerrainDialog.kt
  editor/src/main/com/mbrlabs/mundus/editor/ui/modules/dialogs/tools/DebugRenderDialog.kt
  editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/TerrainGenTab.kt
  editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/generation/HeightmapTab.kt
  editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/terrain/generation/PerlinNoiseTab.kt
  editor/src/main/com/mbrlabs/mundus/editor/ui/modules/outline/OutlineRightClickMenu.kt
Labels: enhancement

#60 Updated libgdx to 1.11.0
  build.gradle
  editor/CHANGES
  gdx-runtime/CHANGES
Labels: blocked

#159 Show new game object name in Outline
  editor/CHANGES
  editor/src/main/com/mbrlabs/mundus/editor/ui/modules/inspector/components/IdentifierWidget.kt
Labels: bug
